#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/

# ---------------------------------------------------- #
# !!! NOTE THAT THIS SCRIPT SHOULD NOT BE SOURCED. !!! #
# ---------------------------------------------------- #

# last complete install: 2024.03.27

# Note: this script can be run as often as you like. It will not attempt to re-install
#       any already installed program, making it a very fast way update some preferences
#       or install additional packages by adding them to the list below.

# Pre-installation checks
#-------------------------------------------------------------------------------

if [ "$USER" == root ]; then
    echo
    echo "'arch_install' should NOT be run as root, nor should it be run with sudo."
    echo "this script should be run [normally] by a user with sudo privileges."
    exit 1
fi

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    echo
    echo "'arch_install' should NOT be sourced."
    exit 1
fi

# Variables
#-------------------------------------------------------------------------------

FORCE=0

# OS Detection
#-------------------------------------------------------------------------------

if [ -f /etc/arch-release ]; then
    OS="arch"
elif [ -f /etc/debian_version ]; then
    OS="debian"
else
    echo "Unsupported OS. This script only supports Arch Linux and Debian/Ubuntu."
    exit 1
fi

# Logging
#-------------------------------------------------------------------------------

mkdir -p $HOME/.local/share
LOG="$HOME/.local/share/arch_install.log"
ERR="$HOME/.local/share/arch_install_errors.log"
printf "PACKAGE INSTALL ($OS)\n\n\n" > "$LOG"
printf "PACKAGE INSTALL ($OS)\n\n\n" > "$ERR"

# User input
#-------------------------------------------------------------------------------

# Ask for password, this will be used for all the sudo calls.:
# and to change the shell later on.
read -s -p "[sudo] password for $USER: " password
echo $password | sudo -S echo '' 2>/dev/null
if [ $? -ne 0 ]; then
    printf "\nIncorrect sudo password. Script ended prematurely.\n\nPlease start over.\n\n"
    exit 1
fi

## Update
#-------------------------------------------------------------------------------

printf "\n\nUpdating (%s)...\n\n" "$OS"
printf "\n\nUpdating (%s)...\n\n" "$OS" >> $LOG
printf "\n\nUpdating (%s)...\n\n" "$OS" >> $ERR
if [ "$OS" = "debian" ]; then
    echo $password | sudo -S apt update -y >> $LOG 2>> $ERR
    echo $password | sudo -S apt upgrade -y >> $LOG 2>> $ERR
elif [ "$OS" = "arch" ]; then
    echo $password | sudo -S pacman -Syu --noconfirm >> $LOG 2>> $ERR
fi


## Custom installation functions
#-------------------------------------------------------------------------------

echo_success(){
    if [ $1 -ne 0 ]; then
        printf "failed!\n"
        printf "\nfailed!\n" >> $LOG
        printf "\nfailed!\n" >> $ERR
        return 1
    fi

    printf "success!\n"
    printf "\nsuccess!\n" >> $LOG
    printf "\nsuccess!\n" >> $ERR
    return 0
}

pkg_install(){ # will only install the first argument!
    printf "installing $1... "
    printf "\n\n\ninstalling $1...\n" >> $LOG
    printf "\n\n\ninstalling $1...\n" >> $ERR

    # check if package is already installed...
    if [ "$OS" = "debian" ]; then
        dpkg -l $1 >> $LOG 2>> $ERR
    elif [ "$OS" = "arch" ]; then
        pacman -Qi $1 >> $LOG 2>> $ERR
    fi
    if [ $? = 0 ] && [ "$FORCE" -eq 0 ]; then
        printf "already installed.\n"
        printf "already installed.\n" >> $LOG
        printf "already installed.\n" >> $ERR
        return 1
    fi

    if [ "$OS" = "debian" ]; then
        printf "sudo apt install -y $1\n" >> $LOG
        printf "sudo apt install -y $1\n" >> $ERR
        echo $password | sudo -S apt install -y $1 >> $LOG 2>> $ERR
    elif [ "$OS" = "arch" ]; then
        printf "sudo pacman -S --noconfirm $1\n" >> $LOG
        printf "sudo pacman -S --noconfirm $1\n" >> $ERR
        echo $password | sudo -S pacman -S --noconfirm $1 >> $LOG 2>> $ERR
    fi
    exit_code=$?
    echo_success $exit_code
    return $exit_code
}


## Start script
## -----------------------------------------------------------------------------------

# Ensure basic dependencies are installed
pkg_install zsh
pkg_install curl
pkg_install git

#chsh -s /usr/bin/zsh #change shell to zsh
echo $password | sudo -S chsh -s /usr/bin/zsh "$USER" >> "$LOG" 2>> "$ERR"

## zoxide
curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh #zoxide
echo $password | sudo -S cp ~/.local/bin/zoxide /usr/local/bin

#zsh autosuggestion
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions

# fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

# zsh syntax hl
rm -rf $HOME/.config/zsh/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting $HOME/.config/zsh/zsh-syntax-highlighting
